[manifest]
version = "1.0.0"
priority = 0

# localize
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''love.graphics.polygon((_type == 'line' or _type == 'line_emboss') and 'line' or "fill", self.pixellated_rect[_type].vertices)'''
position = "at"
payload = '''if self.config.id == 'arrow_badge_color_node' then
    G.SHADERS['arrow_ui_poly']:send('polychrome', {G.TIMERS.REAL/(28), G.TIMERS.REAL})
    G.SHADERS['arrow_ui_poly']:send("time", 123.33412*12.5123152%3000)
    love.graphics.setShader(G.SHADERS['arrow_ui_poly'], G.SHADERS['arrow_ui_poly'])
    love.graphics.polygon((_type == 'line' or _type == 'line_emboss') and 'line' or "fill", self.pixellated_rect[_type].vertices)
    love.graphics.setShader()
else
    love.graphics.polygon((_type == 'line' or _type == 'line_emboss') and 'line' or "fill", self.pixellated_rect[_type].vertices)
end'''
times = 1
match_indent = true
