[manifest]
version = "1.0.0"
priority = 10

#
# Patches jokers that use inconsistent "Xmult" property
#

# Card:update()
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Throwback' then
    self.ability.x_mult = 1 + G.GAME.skips*self.ability.extra
end'''
position = "at"
payload = ''''''
match_indent = true
times = 1

# Card:update()
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == "Joker Stencil" then 
    self.ability.x_mult = (G.jokers.config.card_limit - #G.jokers.cards)
    for i = 1, #G.jokers.cards do
        if G.jokers.cards[i].ability.name == 'Joker Stencil' then self.ability.x_mult = self.ability.x_mult + 1 end
    end
end'''
position = "at"
payload = ''''''
match_indent = true
times = 1

# Card:update()
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Swashbuckler' then
    local sell_cost = 0
    for i = 1, #G.jokers.cards do
        if G.jokers.cards[i] ~= self and (G.jokers.cards[i].area and G.jokers.cards[i].area == G.jokers) then
            sell_cost = sell_cost + G.jokers.cards[i].sell_cost
        end
    end
    self.ability.mult = sell_cost
end'''
position = "at"
payload = ''''''
match_indent = true
times = 1